.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-GENERATE\-CHANGELOG" "1" "May 2020" "" ""
.
.SH "NAME"
\fBgit\-generate\-changelog\fR \- Generate changelog from GitHub
.
.SH "SYNOPSIS"
\fBgit generate\-changelog\fR [\-h|\-\-help] [\-u|\-\-user] [\-p|\-\-project]
.
.SH "DESCRIPTION"
Automatically generate changelog from your tags, issues, labels and pull requests on GitHub\.
.
.SH "OPTIONS"
\-u, \-\-user USER
.
.P
Username of the owner of target GitHub repo\.
.
.P
\-p, \-\-project PROJECT
.
.P
Name of project on GitHub\.
.
.P
\-t, \-\-token TOKEN
.
.P
To make more than 50 requests per hour your GitHub token is required\. You can generate it at: https://github\.com/settings/tokens/new
.
.P
\-f, \-\-date\-format FORMAT
.
.P
Date format\. Default is %Y\-%m\-%d\.
.
.P
\-o, \-\-output NAME
.
.P
Output file\. To print to STDOUT instead, use blank as path\. Default is CHANGELOG\.md\.
.
.P
\-b, \-\-base NAME
.
.P
Optional base file to append generated changes to\. Default is HISTORY\.md\.
.
.P
\-\-summary\-label LABEL
.
.P
Set up custom label for the release summary section\. Default is ""\.
.
.P
\-\-breaking\-label LABEL
.
.P
Set up custom label for breaking changes section\. Default is "\fBBreaking changes:\fR"\.
.
.P
\-\-enhancement\-label LABEL
.
.P
Set up custom label for enhancements section\. Default is "\fBImplemented enhancements:\fR"\.
.
.P
\-\-bugs\-label LABEL
.
.P
Set up custom label for bug\-fixes section\. Default is "\fBFixed bugs:\fR"\.
.
.P
\-\-deprecated\-label LABEL
.
.P
Set up custom label for deprecated section\. Default is "\fBDeprecated:\fR"\.
.
.P
\-\-removed\-label LABEL
.
.P
Set up custom label for removed section\. Default is "\fBRemoved:\fR"\.
.
.P
\-\-security\-label LABEL
.
.P
Set up custom label for security section\. Default is "\fBSecurity:\fR"\.
.
.P
\-\-issues\-label LABEL
.
.P
Set up custom label for closed\-issues section\. Default is "\fBClosed issues:\fR"\.
.
.P
\-\-header\-label LABEL
.
.P
Set up custom header label\. Default is "# Changelog"\.
.
.P
\-\-configure\-sections HASH, STRING
.
.P
Define your own set of sections which overrides all default sections\.
.
.P
\-\-add\-sections HASH, STRING
.
.P
Add new sections but keep the default sections\.
.
.P
\-\-front\-matter JSON
.
.P
Add YAML front matter\. Formatted as JSON because it\'s easier to add on the command line\.
.
.P
\-\-pr\-label LABEL
.
.P
Set up custom label for pull requests section\. Default is "\fBMerged pull requests:\fR"\.
.
.P
\-\-[no\-]issues
.
.P
Include closed issues in changelog\. Default is true\.
.
.P
\-\-[no\-]issues\-wo\-labels
.
.P
Include closed issues without labels in changelog\. Default is true\.
.
.P
\-\-[no\-]pr\-wo\-labels
.
.P
Include pull requests without labels in changelog\. Default is true\.
.
.P
\-\-[no\-]pull\-requests
.
.P
Include pull\-requests in changelog\. Default is true\.
.
.P
\-\-[no\-]filter\-by\-milestone
.
.P
Use milestone to detect when issue was resolved\. Default is true\.
.
.P
\-\-[no\-]issues\-of\-open\-milestones
.
.P
Include issues of open milestones\. Default is true\.
.
.P
\-\-[no\-]author
.
.P
Add author of pull request at the end\. Default is true\.
.
.P
\-\-usernames\-as\-github\-logins
.
.P
Use GitHub tags instead of Markdown links for the author of an issue or pull\-request\.
.
.P
\-\-unreleased\-only
.
.P
Generate log from unreleased closed issues only\.
.
.P
\-\-[no\-]unreleased
.
.P
Add to log unreleased closed issues\. Default is true\.
.
.P
\-\-unreleased\-label LABEL
.
.P
Set up custom label for unreleased closed issues section\. Default is "\fBUnreleased:\fR"\.
.
.P
\-\-[no\-]compare\-link
.
.P
Include compare link (Full Changelog) between older version and newer version\. Default is true\.
.
.P
\-\-include\-labels x,y,z
.
.P
Of the labeled issues, only include the ones with the specified labels\.
.
.P
\-\-exclude\-labels x,y,z
.
.P
Issues with the specified labels will be excluded from changelog\. Default is \'duplicate,question,invalid,wontfix\'\.
.
.P
\-\-summary\-labels x,y,z
.
.P
Issues with these labels will be added to a new section, called "Release Summary"\. The section display only body of issues\. Default is \'Release summary,release\-summary,Summary,summary\'\.
.
.P
\-\-breaking\-labels x,y,z
.
.P
Issues with these labels will be added to a new section, called "Breaking changes"\. Default is \'backwards\-incompatible,breaking\'\.
.
.P
\-\-enhancement\-labels x,y,z
.
.P
Issues with the specified labels will be added to "Implemented enhancements" section\. Default is \'enhancement,Enhancement\'\.
.
.P
\-\-bug\-labels x,y,z
.
.P
Issues with the specified labels will be added to "Fixed bugs" section\. Default is \'bug,Bug\'\.
.
.P
\-\-deprecated\-labels x,y,z
.
.P
Issues with the specified labels will be added to a section called "Deprecated"\. Default is \'deprecated,Deprecated\'\.
.
.P
\-\-removed\-labels x,y,z
.
.P
Issues with the specified labels will be added to a section called "Removed"\. Default is \'removed,Removed\'\.
.
.P
\-\-security\-labels x,y,z
.
.P
Issues with the specified labels will be added to a section called "Security fixes"\. Default is \'security,Security\'\.
.
.P
\-\-issue\-line\-labels x,y,z
.
.P
The specified labels will be shown in brackets next to each matching issue\. Use "ALL" to show all labels\. Default is []\.
.
.P
\-\-exclude\-tags x,y,z
.
.P
Changelog will exclude specified tags\.
.
.P
\-\-exclude\-tags\-regex REGEX
.
.P
Apply a regular expression on tag names so that they can be excluded, for example: \-\-exclude\-tags\-regex "\.*+\ed{1,}"\.
.
.P
\-\-since\-tag x
.
.P
Changelog will start after specified tag\.
.
.P
\-\-due\-tag x
.
.P
Changelog will end before specified tag\.
.
.P
\-\-since\-commit x
.
.P
Fetch only commits after this time\. eg\. "2017\-01\-01 10:00:00"
.
.P
\-\-max\-issues NUMBER
.
.P
Maximum number of issues to fetch from GitHub\. Default is unlimited\.
.
.P
\-\-release\-url URL
.
.P
The URL to point to for release links, in printf format (with the tag as variable)\.
.
.P
\-\-github\-site URL
.
.P
The Enterprise GitHub site where your project is hosted\.
.
.P
\-\-github\-api URL
.
.P
The enterprise endpoint to use for your GitHub API\.
.
.P
\-\-simple\-list
.
.P
Create a simple list from issues and pull requests\. Default is false\.
.
.P
\-\-future\-release RELEASE\-VERSION
.
.P
Put the unreleased changes in the specified release number\.
.
.P
\-\-release\-branch RELEASE\-BRANCH
.
.P
Limit pull requests to the release branch, such as master or release\.
.
.P
\-\-http\-cache
.
.P
Use HTTP Cache to cache GitHub API requests (useful for large repos)\. Default is true\.
.
.P
\-\-[no\-]cache\-file CACHE\-FILE
.
.P
Filename to use for cache\. Default is github\-changelog\-http\-cache in a temporary directory\.
.
.P
\-\-cache\-log CACHE\-LOG
.
.P
Filename to use for cache log\. Default is github\-changelog\-logger\.log in a temporary directory\.
.
.P
\-\-ssl\-ca\-file PATH
.
.P
Path to cacert\.pem file\. Default is a bundled lib/github_changelog_generator/ssl_certs/cacert\.pem\. Respects SSL_CA_PATH\.
.
.P
\-\-require file1\.rb,file2\.rb
.
.P
Paths to Ruby file(s) to require before generating changelog\.
.
.P
\-\-[no\-]verbose
.
.P
Run verbosely\. Default is true\.
.
.P
\-v, \-\-version
.
.P
Print version number\.
.
.P
\-h, \-\-help
.
.P
Displays Help\.
.
.SH "REBASED COMMITS"
GitHub pull requests that have been merged whose merge commit SHA has been modified through rebasing, cherry picking, or some other method may be tracked via a special comment on GitHub\. Git commit SHAs found in comments on pull requests matching the regular expression \fB/rebased commit: ([0\-9a\-f]{40})/i\fR will be used in place of the original merge SHA when being added to the changelog\.
.
.SH "EXAMPLES"
.
.SH "AUTHOR"
Written by Petr Korolev sky4winder@gmail\.com
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/github\-changelog\-generator/github\-changelog\-generator/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/github\-changelog\-generator/github\-changelog\-generator/\fR>
