# These are supported funding model platforms

github: #[skywinder, olleolleolle, ferrarimarco] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: skywinder # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: skywinder # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: ["https://www.paypal.me/sky4winder"]  # Replace with a single custom sponsorship URLko_fi: skywinder

