inherit_from: .rubocop_todo.yml
require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'vendor/**/*'
    - 'gemfiles/**/*'

Layout/LineLength:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Performance/RegexpMatch:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

# http://viget.com/extend/just-use-double-quoted-ruby-strings
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Enabled: false

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
    Exclude:
      - 'spec/**/*'

Naming/FileName:
  Exclude:
    - 'bin/git-generate-changelog'

# TODOS
# Offense count: 14
Metrics/AbcSize:
  Enabled: false

# Offense count: 1
Naming/AccessorMethodName:
  Enabled: false

# Offense count: 10
Style/Documentation:
  Enabled: false

# Offense count: 1
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
# SupportedStyles: skip_modifier_ifs, always
Style/Next:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Enabled: false

Style/MutableConstant:
  Enabled: false

# "Use idx.positive? instead of idx > 0."
Style/NumericPredicate:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Re-enable when merged; https://github.com/bbatsov/rubocop/pull/4756
Lint/InterpolationCheck:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - lib/github_changelog_generator/parser.rb

Style/MixinUsage:
  Exclude:
    - lib/github_changelog_generator/task.rb

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

