inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'vendor/**/*'
    - 'gemfiles/**/*'

Metrics/LineLength:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

#http://viget.com/extend/just-use-double-quoted-ruby-strings
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Configuration parameters: CountComments.
Metrics/ClassLength:
    Enabled: false

# Configuration parameters: CountComments.
Metrics/MethodLength:
    Enabled: false

Style/FileName:
    Exclude:
      - 'bin/git-generate-changelog'

#TODOS
# Offense count: 14
Metrics/AbcSize:
  Enabled: false

# Offense count: 1
Style/AccessorMethodName:
  Enabled: false

# Offense count: 10
Style/Documentation:
  Enabled: false

# Offense count: 1
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
# SupportedStyles: skip_modifier_ifs, always
Style/Next:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Enabled: false

Style/MutableConstant:
    Enabled: false

# "Use idx.positive? instead of idx > 0."
Style/NumericPredicate:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
